name: Semgrep SAST Scan

on:
  push:
    branches: [ "master" ] 

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" returntocorp/semgrep semgrep scan --config auto

          